name: Build niri

on:
    push:
        branches: ["main"]
    pull_request:
        branches: ["main"]
    workflow_dispatch:

jobs:
    build-niri:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v6
              with:
                  submodules: true

            - name: Build niri deb
              uses: devcontainers/ci@v0.3
              with:
                  cacheFrom: ghcr.io/michaelmnemonic/niri-devcontainer
                  push: never
                  runCmd: |
                    cd /workspaces/niri-debian/niri
                    cargo deb

            - name: Upload artifact
              uses: actions/upload-artifact@v6
              with:
                  name: niri-binary
                  path: ${{ github.workspace }}/niri/target/debian
